services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - "4318:4318" # OTLP http receiver
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - COLLECTOR_LOCATION=local docker-compose
      - COLLECTOR_NAME=frankie
