#!/bin/bash

set -x

npm run clean

npm run build

if [[ ! -f ./dist/index.html ]]; then
  echo "Build made no output. Is it that crappy module in .parcelrc? try deleting it and building again"
  exit 1
fi

# dependencies: cowsay, aws (logged in), docker, kubectl (configured)

docker build -t quiz-booth-game:latest .

ECR_URL=414852377253.dkr.ecr.$(aws configure get region).amazonaws.com
REPO_NAME=quiz-booth-game

# only needs to be done once per hr or so, but it's SO PAINFUL when I forget
if [[ $1 == "faster" ]]; then
  echo "Skipping docker login"
else
  echo "logging in to docker"
  aws ecr get-login-password --region $(aws configure get region) | docker login --username AWS --password-stdin $ECR_URL
fi

if ! git diff --quiet HEAD; then 
   cowsay "Watch out! You have uncommitted changes. The deploy won't work without a fresh commit"
fi

sha=$(git rev-parse HEAD)
whole_docker_id=$ECR_URL/$REPO_NAME:$sha
docker tag $REPO_NAME $whole_docker_id
docker push $whole_docker_id

cat ./deployment.yaml | sed "s#TAGGYDOOBER#$whole_docker_id#" | kubectl apply -f -

./create-honeycomb-marker.sh
