#!/bin/bash

# This script assumes that you've logged into pulumi and chosen its stack

set -e
set -x

npm run clean

npm run build

cd infra

pulumi up --yes

# Create deployment marker after successful deploy
cd ..
echo "Creating deployment marker..."
source .be && ./scripts/create-marker.sh
