#!/bin/bash
# dependency: http-server

# Run the local collector


echo "starting frontend collector"
docker-compose -f ./local-collector/docker-compose.yml up -d

# start up the JS buildy stuff
npm run serve &

cd test/fake-backend

if [[ ! -d "node_modules" ]]; then
  npm install
fi

npm run start
