#!/bin/bash
# dependency: http-server

# Run the local collector

if [[ -d "../observaquiz-api/" ]]; then
  echo "Starting collector as defined in observaquiz-api"
  docker-compose -f ../observaquiz-api/local-collector/docker-compose.yml up -d
else
  echo "starting sad little frontend collector"
  docker-compose -f ./local-collector/docker-compose.yml up -d
fi

cd test/fake-backend

if [[ ! -d "node_modules" ]]; then
  npm install
fi

npm run start
